name: molssi-actcms-molecular-representations
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - comm=0.2.2
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.4
  - ipython=8.25.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.2
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.11.9
  - python-dateutil=2.9.0
  - python_abi=3.11
  - pyzmq=26.0.3
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - pip:
      - aimsim-core==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - astartes==1.3.1
      - attrs==23.2.0
      - bel-resources==0.0.3
      - bioregistry==0.11.9
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - chemprop==2.2.0
      - click==8.1.7
      - click-plugins==1.1.1
      - configargparse==1.7.1
      - contourpy==1.2.1
      - curies==0.7.9
      - cycler==0.12.1
      - descriptastorus==2.8.0
      - dill==0.4.0
      - filelock==3.18.0
      - fonttools==4.53.0
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - greenlet==3.0.3
      - humanize==4.9.0
      - idna==3.7
      - ipywidgets==8.1.7
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.5
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - mhfp==1.9.6
      - mordredcommunity==2.0.6
      - more-click==0.1.2
      - more-itertools==10.3.0
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.18
      - multisplitby==0.0.1
      - networkx==3.3
      - numpy==1.26.4
      - padelpy==0.1.16
      - pandas==2.2.2
      - pandas-flavor==0.7.0
      - pillow==10.3.0
      - propcache==0.3.2
      - psycopg2-binary==2.9.9
      - py3dmol==2.1.0
      - pybel==0.15.5
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pyparsing==3.1.2
      - pystow==0.5.4
      - pytorch-lightning==2.5.1.post0
      - pytrie==0.4.0
      - pytz==2024.1
      - pyyaml==6.0.2
      - ratelimit==2.2.1
      - rdkit==2023.9.6
      - rdkit-pypi==2022.9.5
      - referencing==0.35.1
      - requests==2.32.3
      - requests-file==2.1.0
      - rich==14.0.0
      - rpds-py==0.18.1
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.31
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - torch==2.2.2
      - torchmetrics==1.7.3
      - tqdm==4.66.4
      - tzdata==2024.1
      - urllib3==2.2.2
      - widgetsnbextension==4.0.14
      - xarray==2025.6.1
      - yarl==1.20.1
